"""Change name of status to pusblisied from model Post

Revision ID: 052cf15ff7d8
Revises: e3af63fa3ebf
Create Date: 2021-01-02 21:52:47.797159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052cf15ff7d8'
down_revision = 'e3af63fa3ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('publishied', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_posts_publishied'), 'posts', ['publishied'], unique=False)
    op.drop_index('ix_posts_status', table_name='posts')
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', sa.BOOLEAN(), nullable=True))
    op.create_index('ix_posts_status', 'posts', ['status'], unique=False)
    op.drop_index(op.f('ix_posts_publishied'), table_name='posts')
    op.drop_column('posts', 'publishied')
    # ### end Alembic commands ###
