"""Ad field url_image to Post model

Revision ID: e3af63fa3ebf
Revises: a8d97a86c0fd
Create Date: 2020-12-27 00:13:16.409759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3af63fa3ebf'
down_revision = 'a8d97a86c0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('url_image', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'url_image')
    # ### end Alembic commands ###
