export const POSTS_LIST_REQUEST = "[Post] POSTS_LIST_REQUEST";
export const POSTS_LIST_SUCCESS = "[Post] POSTS_LIST_SUCCESS";
export const POSTS_LIST_FAIL = "[Post] POSTS_LIST_FAIL";

export const POST_DETAILS_REQUEST = "[Post] POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "[Post] POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL = "[Post] POST_DETAILS_FAIL";
